[project]
name = "west-consumer"
version = "0.1.0"
description = "West Consumer"
authors = [
    { name = "lukaszlacinski", email = "lukasz@uchicago.edu" },
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "attrs>=25.3.0,<26.0.0",
    "boto3>=1.35.49,<2.0.0",
    "confluent-kafka>=2.6.0,<3.0.0",
    "esgf-core-utils>=1.1.0,<2.0.0",
    "globus-sdk>=3.46.0,<4.0.0",
    "jsonpatch>=1.33,<2.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "supervisor>=4.2.5,<5.0.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "isort>=6.0.0",
]

[tool.uv]
package = false

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
