[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:west-consumer]
command=python main.py
directory=/var/task
numprocs=6
process_name=consumer-%(process_num)02d
autostart=true
autorestart=false
environment=CONSUMER_INSTANCE="%(process_num)s"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
